version: '3'
services:
  jxstrapiapp:
    image: nestjsprismakit
    container_name: nestjsprismakit
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped
    ports:
      - "8001:8001"